CREATE TABLE employer_profiles
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id             BIGINT                                  NOT NULL,
    company_name        VARCHAR(255)                            NOT NULL,
    company_description TEXT,
    website             VARCHAR(255),
    location            VARCHAR(255)                            NOT NULL,
    address             VARCHAR(255)                            NOT NULL,
    industry            VARCHAR(255)                            NOT NULL,
    company_size        VARCHAR(255)                            NOT NULL,
    founded_year        INTEGER,
    company_logo_url    VARCHAR(255)                            NOT NULL,
    facebook_url        VARCHAR(255),
    linkedin_url        VARCHAR(255),
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_employer_profiles PRIMARY KEY (id)
);

CREATE TABLE job_applications
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    seeker_id    BIGINT                                  NOT NULL,
    job_id       BIGINT                                  NOT NULL,
    status       VARCHAR(255),
    cover_letter TEXT,
    applied_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_job_applications PRIMARY KEY (id)
);

CREATE TABLE job_categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description TEXT,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_job_categories PRIMARY KEY (id)
);

CREATE TABLE job_posting
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title            VARCHAR(255),
    description      TEXT,
    requirement      TEXT,
    qualification    TEXT,
    benefits         TEXT,
    experience_level VARCHAR(255),
    deadline         date,
    location         VARCHAR(255),
    job_type         VARCHAR(255),
    min_salary       DECIMAL(10, 2),
    max_salary       DECIMAL(10, 2),
    job_status       VARCHAR(255),
    category_id      BIGINT,
    employer_id      BIGINT,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_job_posting PRIMARY KEY (id)
);

CREATE TABLE seeker_profiles
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    bio        TEXT,
    skills     TEXT,
    experience TEXT,
    education  TEXT,
    resume_url VARCHAR(255),
    location   VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_seeker_profiles PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name  VARCHAR(255),
    email      VARCHAR(255),
    password   VARCHAR(255),
    role       VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE job_applications
    ADD CONSTRAINT uc_63b0ce1095d831e69bdcf366a UNIQUE (seeker_id, job_id);

ALTER TABLE employer_profiles
    ADD CONSTRAINT uc_employer_profiles_user UNIQUE (user_id);

ALTER TABLE job_categories
    ADD CONSTRAINT uc_job_categories_name UNIQUE (name);

ALTER TABLE seeker_profiles
    ADD CONSTRAINT uc_seeker_profiles_user UNIQUE (user_id);

ALTER TABLE employer_profiles
    ADD CONSTRAINT FK_EMPLOYER_PROFILES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE job_applications
    ADD CONSTRAINT FK_JOB_APPLICATIONS_ON_JOB FOREIGN KEY (job_id) REFERENCES job_posting (id);

ALTER TABLE job_applications
    ADD CONSTRAINT FK_JOB_APPLICATIONS_ON_SEEKER FOREIGN KEY (seeker_id) REFERENCES seeker_profiles (id);

ALTER TABLE job_posting
    ADD CONSTRAINT FK_JOB_POSTING_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES job_categories (id);

ALTER TABLE job_posting
    ADD CONSTRAINT FK_JOB_POSTING_ON_EMPLOYER FOREIGN KEY (employer_id) REFERENCES employer_profiles (id);

ALTER TABLE seeker_profiles
    ADD CONSTRAINT FK_SEEKER_PROFILES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);