CREATE TABLE job_categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description TEXT,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_job_categories PRIMARY KEY (id)
);


ALTER TABLE job_posting
    ADD category_id BIGINT;

ALTER TABLE job_categories
    ADD CONSTRAINT uc_job_categories_name UNIQUE (name);

ALTER TABLE job_posting
    ADD CONSTRAINT FK_JOB_POSTING_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES job_categories (id);

